---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: windows-2016
  #- name: ubuntu-16.04
  #- name: centos-7
    #driver:
      #box: tas50/windows-2016

suites:
  - name: default
    run_list:
      - recipe[samples::default]
      #- recipe[samples::example14]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
